apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: superset
spec:
  generators:
    - clusters:
        values:
          path: superset
  template:
    metadata:
      name: 'superset-{{name}}'
      labels:
        appset: superset
      annotations:
        version: '{{values.path}}'
    spec:
      project: cluster-addons-deploy
      source:
        repoURL: 'https://sibomsa@bitbucket.org/vaimo/rke2_sibos_test_addons.git'
        targetRevision: HEAD
        path: 'addons/{{values.path}}'
      destination:
        name: '{{name}}'
        namespace: superset
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - PrunePropagationPolicy=foreground
          - CreateNamespace=true
          - PruneLast=true
        retry:
          limit: 2
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
